#!/bin/bash -x
BAYAN_PATH=${HOME}/bayan
source ${BAYAN_PATH}/bayan.conf

batman_begins() {
    #Dark Knight Rises
    ip link set mtu 1532 dev $mesh_if
    iwconfig $mesh_if mode ad-hoc essid bnets-mesh ap 00:01:02:03:04:05 channel 1
    batctl if add $mesh_if
    ip link set up dev $mesh_if
    ip link set up dev ${neigh_if}
    ip addr add ${mesh_ip} dev ${neigh_if}
    ip route add ${mesh_ip%.*}.0/24 dev ${neigh_if} proto kernel scope link src ${mesh_ip}
}

clean_table() {
	gw_count=`wc -l ${BAYAN_PATH}/conn.lst | awk '{print $1}'`
	for N in $(seq 1 $gw_count)
	do
		gw=$(cat ${BAYAN_PATH}/conn.lst | awk -v n="$N" 'NR==n {print $1}')
		intf=$(cat ${BAYAN_PATH}/conn.lst | awk -v n="$N" 'NR==n {print $2}')
		prob=$(cat ${BAYAN_PATH}/conn.lst | awk -v n="$N" 'NR==n {print $3}')

		iptables -t mangle -D PREROUTING ${N}

		iptables -t mangle -F MARK${N}
		iptables -t mangle -X MARK${N}
	done
}

restore() {
    ip rule flush && ${BAYAN_PATH}/iprule.ORIGINAL
    clean_table
    iptables-restore < ${BAYAN_PATH}/iptables.ORIGINAL

    gw_count=`wc -l ${BAYAN_PATH}/conn.lst | awk '{print $1}'`
    for N in $(seq 1 $gw_count)
    do
        ip route flush table ${N}
    done
}

load() { #Loads conn.lst
    iptables -t nat -A POSTROUTING -j MASQUERADE
    gw_count=`wc -l ${BAYAN_PATH}/conn.lst | awk '{print $1}'`
    for N in $(seq 1 $gw_count)
    do
        gw=$(cat ${BAYAN_PATH}/conn.lst | awk -v n="$N" 'NR==n {print $1}')
        intf=$(cat ${BAYAN_PATH}/conn.lst | awk -v n="$N" 'NR==n {print $2}')
        prob=$(cat ${BAYAN_PATH}/conn.lst | awk -v n="$N" 'NR==n {print $3}')

        ip rule add fwmark ${N} table ${N}
        ip route add ${mesh_ip%.*}.0/24 dev ${neigh_if} proto kernel scope link src ${mesh_ip} table ${N}
        ip route add ${homenet_ip%.*}.0/24 dev ${homenet_if} proto kernel scope link src ${homenet_ip} table ${N}
        ip route add default via ${gw} dev ${intf} table ${N}

        iptables -t mangle -N MARK${N}
        iptables -t nat -N MARK${N}
        iptables -t nat -I POSTROUTING ${N} -m mark --mark ${N} -j MARK${N}
        iptables -t mangle -A MARK${N} -j MARK --set-mark ${N}
        iptables -t mangle -A MARK${N} -j CONNMARK --save-mark

        iptables -t mangle -I PREROUTING ${N} -i ${client_if} -m conntrack --ctstate     NEW -m statistic --mode random --probability ${prob} -j MARK${N}
    done

    iptables-save > ${BAYAN_PATH}/bayan_iptables
    ip rule save > ${BAYAN_PATH}/bayan_iprules
}

case "$1" in
    "start")
        restore
        ip rule restore < ${BAYAN_PATH}/bayan_iprules
        iptables-restore < ${BAYAN_PATH}/bayan_iptables

        if [[ "$neigh_if" == "bat0" ]]; then
            batman_begins
        fi
        gw_count=`wc -l ${BAYAN_PATH}/conn.lst | awk '{print $1}'`
        for N in $(seq 1 $gw_count)
        do
            ip route add ${mesh_ip%.*}.0/24 dev ${neigh_if} proto kernel scope link src ${mesh_ip} table ${N}
            ip route add ${homenet_ip%.*}.0/24 dev ${homenet_if} proto kernel scope link src ${homenet_ip} table ${N}
            ip route add default via ${gw} dev ${intf} table ${N}
        done
    ;;

    "install")
        iptables-save > ${BAYAN_PATH}/iptables.ORIGINAL

	echo "#!/bin/bash" > iprule.ORIGINAL
	ip rule show | sed 's/[:-]/ /g' | awk '$0="ip rule add priority "$0' >> ${BAYAN_PATH}/iprule.ORIGINAL
	chmod +x iprule.ORIGINAL

        if [[ "$neigh_if" == "bat0" ]]; then
            batman_begins
        fi
        load
        ln -s ${BAYAN_PATH}/bayan /usr/local/sbin
    ;;

    "uninstall")
        rm /usr/local/sbin/bayan
        rm ${BAYAN_PATH}/bayan_iptables
        rm ${BAYAN_PATH}/bayan_iprules
        rm ${BAYAN_PATH}/iptables.ORIGINAL
        rm ${BAYAN_PATH}/iprule.ORIGINAL
    ;;

    "add")
        restore
        echo "${2} ${3} ${4}" >> ${BAYAN_PATH}/conn.lst
        load
    ;;

    "remove")
        if [ "$2" -eq 1 ]; then
            echo "You can't delete conn#1"
            exit 0
        fi
        restore
        sed -i $2 ${BAYAN_PATH}/conn.lst
        load
    ;;

    "show")
        conn_cnt=$(iptables -t nat -nvL | grep -c "Chain MARK")
        conn_id=1
        for conn in $(seq 1 $conn_cnt)
            do
            conn_ip=$(ip route show table ${conn} | grep "default via" | awk '{print $3}')
            prob=$(iptables -t mangle -nvL | grep "MARK${conn}.*probability" | awk '{print $NF}')
            echo "${conn_id}: ${conn}   ${conn_ip}      ${prob}"
            conn_id=$(( conn_id + 1 ))
        done
    ;;

    *)
        echo "You have failed to specify what to do correctly."
        exit 1
        ;;
esac
